import React, { useState } from 'react';
import { BookOpen, Copy, Check, Terminal, ShieldAlert, Sparkles, Code2 } from 'lucide-react';
import { PersonaProfile } from '../types';

interface DirectivesGuideProps {
  activePersona: PersonaProfile | null;
}

export const DirectivesGuide: React.FC<DirectivesGuideProps> = ({ activePersona }) => {
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  const copyToClipboard = (key: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(key);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const sampleJsonPayload = activePersona
    ? JSON.stringify(
        {
          model: 'gemini-3.6-flash',
          systemInstruction: activePersona.compiledSystemInstruction,
          userMessage: 'What is your opinion on slow development cycles?'
        },
        null,
        2
      )
    : `{
  "model": "gemini-3.6-flash",
  "systemInstruction": "You are a high-fidelity behavior, style, and tone replica...",
  "userMessage": "Sample prompt"
}`;

  return (
    <div className="max-w-5xl mx-auto py-2 space-y-8">
      {/* Banner */}
      <div className="bg-slate-900/80 backdrop-blur-md border border-slate-800/80 rounded-2xl p-6 space-y-3 shadow-xl">
        <div className="flex items-center gap-2 text-indigo-400 font-mono text-xs font-bold uppercase tracking-wider">
          <BookOpen className="h-4 w-4" />
          <span>Operational Directives Framework</span>
        </div>
        <h2 className="text-2xl font-bold text-white">Replica Engineering Specification</h2>
        <p className="text-xs text-slate-300 max-w-2xl leading-relaxed font-medium">
          Every replica generated by the Persona Replica Engine enforces the 4 core Operational Directives to guarantee 100% style, vocabulary, and behavioral replication without AI filler.
        </p>
      </div>

      {/* 4 Directives Breakdown */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="bg-slate-900/80 backdrop-blur-md border border-slate-800/80 rounded-2xl p-5 space-y-2 shadow-xl hover:border-slate-700 transition-all">
          <div className="flex items-center justify-between">
            <div className="text-xs font-mono font-bold text-indigo-400">01 // TONE & VOCABULARY</div>
            <span className="text-[10px] font-mono font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
              Linguistic Casing
            </span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed font-medium">
            Adopts the exact slang, casing (all-lowercase vs capitalized), punctuation style, and terminology used in the reference data. Matches directness, energy, and brevity.
          </p>
        </div>

        <div className="bg-slate-900/80 backdrop-blur-md border border-slate-800/80 rounded-2xl p-5 space-y-2 shadow-xl hover:border-slate-700 transition-all">
          <div className="flex items-center justify-between">
            <div className="text-xs font-mono font-bold text-slate-200">02 // THINKING FRAMEWORK</div>
            <span className="text-[10px] font-mono font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-slate-800 text-slate-300 border border-slate-700">
              Mental Models
            </span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed font-medium">
            Adopts specific mental models, priorities, worldviews, biases, and references (technical concepts, personal habits, preferred topics, or jokes).
          </p>
        </div>

        <div className="bg-slate-900/80 backdrop-blur-md border border-slate-800/80 rounded-2xl p-5 space-y-2 shadow-xl hover:border-slate-700 transition-all">
          <div className="flex items-center justify-between">
            <div className="text-xs font-mono font-bold text-amber-400">03 // NO CONVERSATIONAL FILLER</div>
            <span className="text-[10px] font-mono font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-amber-500/20 text-amber-300 border border-amber-500/30">
              Zero Character Break
            </span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed font-medium">
            Never break character, never explain "As an AI...", and never hedge with standard assistant responses like "How can I help you today?". Answer strictly as the person would answer.
          </p>
        </div>

        <div className="bg-slate-900/80 backdrop-blur-md border border-slate-800/80 rounded-2xl p-5 space-y-2 shadow-xl hover:border-slate-700 transition-all">
          <div className="flex items-center justify-between">
            <div className="text-xs font-mono font-bold text-emerald-400">04 // REASONING & EXTRAPOLATION</div>
            <span className="text-[10px] font-mono font-bold uppercase tracking-wider px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
              Context Logic
            </span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed font-medium">
            If asked about a scenario not explicitly in the reference text, extrapolates how this person would react based on their established mindset, tone, and decision-making logic.
          </p>
        </div>
      </div>

      {/* API Payload & Integration Box */}
      <div className="bg-slate-900/80 backdrop-blur-md border border-slate-800/80 rounded-2xl p-6 space-y-4 shadow-xl">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Code2 className="h-5 w-5 text-indigo-400" />
            <h3 className="text-sm font-bold text-white">Ready-To-Use API Payload Snippet</h3>
          </div>

          <button
            onClick={() => copyToClipboard('payload', sampleJsonPayload)}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-mono border border-slate-700 transition-all cursor-pointer"
          >
            {copiedSection === 'payload' ? (
              <>
                <Check className="h-3.5 w-3.5 text-emerald-400" />
                <span className="text-emerald-400 font-bold">Copied</span>
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5 text-slate-400" />
                <span>Copy JSON</span>
              </>
            )}
          </button>
        </div>

        <pre className="bg-slate-950 p-4 rounded-xl border border-slate-800 text-xs font-mono text-emerald-400 overflow-x-auto leading-relaxed">
          {sampleJsonPayload}
        </pre>
      </div>
    </div>
  );
};
